---
title: C6320 | Microsoft Docs
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: cffb779f2b92cfee495480e2a1ba4946c5def605
ms.sourcegitcommit: af428c7ccd007e668ec0dd8697c88fc5d8bca1e2
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 11/16/2018
ms.locfileid: "51798118"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

avviso C6320: espressione di filtro eccezioni è la costante EXCEPTION_EXECUTE_HANDLER. Questa condizione potrebbe mascherare le eccezioni che non erano destinate a essere gestiti  
  
 Questo avviso indica l'effetto collaterale dell'utilizzo della costante EXCEPTION_EXECUTE_HANDLER in except block. In questo caso, l'istruzione nel \_blocco except venga sempre eseguita per gestire l'eccezione, incluse le eccezioni non desiderato per la gestione in una determinata funzione. È consigliabile verificare l'eccezione prima che la sua gestione.  
  
## <a name="example"></a>Esempio  
 Il codice seguente genera questo avviso perché except block will tenta di gestire le eccezioni di tutti i tipi:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Per risolvere questo problema, utilizzare `GetExceptionCode` per verificare la presenza di una particolare eccezione prima di gestirla, come illustrato nel codice seguente:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Vedere anche  
 [Istruzione try-except](http://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)



