---
title: C6312
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 74ea9c013996ba29a3e29b724c41c3cac1e12127
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 04/26/2018
---
# <a name="c6312"></a>C6312
avviso C6312: possibile ciclo infinito: utilizzo della costante EXCEPTION_CONTINUE_EXECUTION nell'espressione di filtro eccezioni di un blocco try-tranne

 Questo avviso indica l'utilizzo della costante `EXCEPTION_CONTINUE_EXECUTION` (o un'altra costante che restituisce -1) nell'espressione di filtro di un gestore eccezioni strutturate. Utilizzo del valore della costante `EXCEPTION_CONTINUE_EXECUTION` potrebbe causare un ciclo infinito. Ad esempio, se è stata generata un'eccezione dall'hardware, l'istruzione che ha causato l'eccezione verrà riavviato. Se l'indirizzo che ha causato l'eccezione non è ancora valido, un'altra eccezione si verifica e di essere gestita nello stesso modo. In questo modo un ciclo infinito.

 Una chiamata esplicita a `RaiseException` non causerà direttamente un ciclo infinito, ma continuerà l'esecuzione del codice nel blocco protetto. Questo può essere imprevisto e può comportare un ciclo infinito se `RaiseException` utilizzato per evitare la dereferenziazione di un puntatore non valido.

 In genere, `EXCEPTION_CONTINUE_EXECUTION` deve essere restituita solo una funzione chiamata nell'espressione di filtro, che ha la possibilità di correggere il puntatore che ha causato l'eccezione o la memoria sottostante.

## <a name="example"></a>Esempio
 Il codice seguente genera questo avviso:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Per risolvere il problema, utilizzare il codice seguente:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```