---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 03552bd5990b2533ad6632bbe86776d21afe32ee
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/06/2019
ms.locfileid: "74878138"
---
# <a name="c6312"></a>C6312
avviso C6312: Possibile ciclo infinito: utilizzo della costante EXCEPTION_CONTINUE_EXECUTION nell'espressione exception-filter di un try-except

 Questo avviso indica l'utilizzo della costante `EXCEPTION_CONTINUE_EXECUTION` (o di un'altra costante che restituisce-1) nell'espressione di filtro di un gestore di eccezioni strutturate. L'uso del valore costante `EXCEPTION_CONTINUE_EXECUTION` potrebbe causare un ciclo infinito. Se, ad esempio, un'eccezione è stata generata dall'hardware, l'istruzione che ha causato l'eccezione verrà riavviata. Se l'indirizzo che ha causato l'eccezione è ancora negativo, si verificherà un'altra eccezione che verrà gestita nello stesso modo. Questo causa un ciclo infinito.

 Una chiamata esplicita a `RaiseException` non genererà direttamente un ciclo infinito, ma continuerà l'esecuzione del codice nel blocco protetto. Questo può essere imprevisto e potrebbe causare un ciclo infinito se `RaiseException` è stato usato per evitare di dereferenziare un puntatore non valido.

 In genere, `EXCEPTION_CONTINUE_EXECUTION` deve essere restituito solo da una funzione chiamata nell'espressione di filtro, che ha la possibilità di correggere il puntatore che ha causato l'eccezione o la memoria sottostante.

## <a name="example"></a>Esempio
 Il codice seguente genera questo avviso:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Per correggere il problema, usare il codice seguente:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```
