---
title: C6312
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: caa2044c9bd36e8e7953bf2e7b1162f347bc8e04
ms.sourcegitcommit: 37fb7075b0a65d2add3b137a5230767aa3266c74
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 01/02/2019
ms.locfileid: "53890219"
---
# <a name="c6312"></a>C6312
avviso C6312: Possibile ciclo infinito: utilizzo della costante EXCEPTION_CONTINUE_EXECUTION nell'espressione exception-filter di un blocco try-tranne

 Questo avviso indica l'utilizzo della costante `EXCEPTION_CONTINUE_EXECUTION` (o un'altra costante che restituisce -1) nell'espressione di filtro di un gestore di eccezioni strutturate. Uso del valore della costante `EXCEPTION_CONTINUE_EXECUTION` potrebbe causare un ciclo infinito. Ad esempio, se è stata generata un'eccezione dall'hardware, l'istruzione che ha causato l'eccezione verrà riavviato. Se l'indirizzo che ha causato l'eccezione non è ancora valido, un'altra eccezione avrà luogo ed essere gestita nello stesso modo. Ciò causa un ciclo infinito.

 Una chiamata esplicita a `RaiseException` non causerà direttamente un ciclo infinito, ma continuerà l'esecuzione del codice in un blocco protetto. Questo può essere imprevisto e potrebbe causare un ciclo infinito se `RaiseException` utilizzato per evitare la dereferenziazione di un puntatore non valido.

 In genere, `EXCEPTION_CONTINUE_EXECUTION` deve essere restituita solo se una funzione denominata nell'espressione di filtro, che ha la possibilità di correggere il puntatore che ha causato l'eccezione o la memoria sottostante.

## <a name="example"></a>Esempio
 Il codice seguente genera questo avviso:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Per risolvere questo problema, usare il codice seguente:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```