---
title: C6320 | Documenti Microsoft
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C6320
helpviewer_keywords: C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: "10"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload: multiple
ms.openlocfilehash: dbf498f943fb4f6e446cd254e7ca5f844ee0ec68
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/22/2017
---
# <a name="c6320"></a>C6320
avviso C6320: espressione di filtro eccezioni è la costante EXCEPTION_EXECUTE_HANDLER. Questa condizione potrebbe mascherare eccezioni che non erano destinate a essere gestiti  
  
 Questo avviso indica l'effetto collaterale dell'utilizzo della costante EXCEPTION_EXECUTE_HANDLER in except block. In questo caso, l'istruzione nel \_blocco except verrà sempre eseguito per gestire l'eccezione, incluse le eccezioni che non si desidera gestire in una determinata funzione. È consigliabile verificare che l'eccezione prima di gestirla.  
  
## <a name="example"></a>Esempio  
 Il codice seguente genera questo avviso perché except blocco tenta di gestire le eccezioni di tutti i tipi:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Per risolvere questo problema, utilizzare `GetExceptionCode` per verificare la presenza di una particolare eccezione prima di gestirla, come illustrato nel codice seguente:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Vedere anche  
 [Istruzione try-except](/cpp/cpp/try-except-statement)